apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: {{ include "db.fullname" . }}
              containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "db.fullname" . }}
                key: mysql_rootpassword  
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "db.fullname" . }}
                key: mysql_user            
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "db.fullname" . }}
                key: mysql_password
          volumeMounts:
          - name: {{ include "db.fullname" . }}-persistent-storage
            mountPath: /var/lib/mysql
          - name: {{ include "db.fullname" . }}-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: {{ include "db.fullname" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "db.fullname" . }}

      - name: {{ include "db.fullname" . }}-initdb
        secret:
          secretName: {{ include "db.fullname" . }}
          items:
          - key: init_sh
            path: init.sh
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
