apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
type: Opaque
data:
  mysql_rootpassword: a2VlcGNvZGluZzIwMjI=
  mysql_user: bXljb250YWRvcg==
  mysql_password: b3NpdG9kZXBlbHVjaGU=
  init_sh: bXlzcWwgLS1wYXNzd29yZD1rZWVwY29kaW5nMjAyMiAtdSByb290IDw8RU9TCkNSRUFURSBEQVRBQkFTRSBJRiBOT1QgRVhJU1RTIGNvbnRhZG9yZGI7CkdSQU5UIEFMTCBPTiBjb250YWRvcmRiLiogVE8gJ215Y29udGFkb3InOwpGTFVTSCBQUklWSUxFR0VTOwogICAgClVTRSBjb250YWRvcmRiOwoKQ1JFQVRFIFRBQkxFIHRhYmxhX2NvbnRhZG9yICgKICAgIGNvbnRhZG9yIGludCBOT1QgTlVMTAopOwoKSU5TRVJUIElOVE8gdGFibGFfY29udGFkb3IgVkFMVUVTICgwKTsKRU9T