version: '3.3'

services:
  app:
    environment:
      MYSQL_DB: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: $MYSQL_HOST
      FLASK_APP: $FLASK_APP
      FLASK_ENV: $FLASK_ENV
      FLASK_RUN_HOST: $FLASK_RUN_HOST
    #build: .
    image: crisgarcia/app-python:1.0.0
    ports:
     - 5000:5000
    depends_on:
      - db01
  db01:
    image: mysql
    environment:
     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
     MYSQL_DATABASE: $MYSQL_DB
     MYSQL_USER: $MYSQL_USER
     MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
     - "./db.sh:/docker-entrypoint-initdb.d/db.sh"
     - "mysql-data:/var/lib/mysql"

volumes:
 mysql-data:
