apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  mysql_user: bXljb250YWRvcg==
  mysql_password: b3NpdG9kZXBlbHVjaGU=
  mysql_db: Y29udGFkb3JkYg==